//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.DropDownList ddlStations;
		
		protected System.Web.UI.WebControls.Button b1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divDetails;
		
		protected System.Web.UI.WebControls.Label lblStation;
		
		protected System.Web.UI.WebControls.Label lblBorough;
		
		protected System.Web.UI.WebControls.Label lbloutagedate;
		
		protected System.Web.UI.WebControls.Label lblestimatedreturntoservice;
		
		protected System.Web.UI.WebControls.Label lblreasons;
		
		protected System.Web.UI.WebControls.Label lblequipment;
		
		protected System.Web.UI.WebControls.Label lblADA;
	}
}
